import smtplib
from email.message import EmailMessage
from datetime import datetime
import os

#EMAIL CONFIG
SENDER_EMAIL = ""
SENDER_PASSWORD = ""  
RECEIVER_EMAIL = ""

#DUMMY GPS COORDINATES
LATITUDE = "27.7172"
LONGITUDE = "85.3240"

#IMAGE PATH
IMAGE_PATH = "D:\ECE Engineering\Major Project\Email Alert\Screenshot 2026-01-03 105001.png"

#DATE & TIME
current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

#CREATE EMAIL
msg = EmailMessage()
msg["From"] = SENDER_EMAIL
msg["To"] = RECEIVER_EMAIL
msg["Subject"] = "Road Damage Detected – Alert Notification"

msg.set_content(f"""
Dear Authority,

A road damage has been detected by the monitoring system.

📅 Date & Time: {current_time}
📍 Location (GPS):
   Latitude: {LATITUDE}
   Longitude: {LONGITUDE}

Please find the attached image for verification.

This is an automated alert generated by the Road Condition Detection System.

""")

#ATTACH IMAGE
if os.path.exists(IMAGE_PATH):
    with open(IMAGE_PATH, "rb") as img:
        msg.add_attachment(
            img.read(),
            maintype="image",
            subtype="jpeg",
            filename=os.path.basename(IMAGE_PATH)
        )

#SEND EMAIL
try:
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        print("✅ Email sent successfully!")

except Exception as e:
    print("❌ Failed to send email:", e)
